// This Smart contract was auto generated by EthairBaloons 
// https://github.com/petrosDemetrakopoulos/ethairballoons
// SPDX-License-Identifier: UNLICENSED
pragma solidity >=0.6.2;
pragma experimental ABIEncoderV2;

contract HealthContract {
	string public dataId;
	uint public numberOfRecords = 0;
	string[] public recordsList;

	event dataAdded(string dat);

	struct Block {
		string payload;
		uint listPointer;
	}

	mapping(string => Block) public facts;

	function isRecord(string recordAddress) internal view returns (bool isRec) {
		if(recordsList.length == 0) return false;
		return (recordsList[facts[recordAddress].listPointer] == recordAddress);
	}

	function getRecordCount() external view returns (uint recCount){
		return recordsList.length;
	}

	function addRecord(string memory payload, string ID) external returns (bool success) {
		if(isRecord(ID)) revert('record with this id already exists');
		facts[ID].payload = payload;
		recordsList.push(ID);
		facts[ID].listPointer = recordsList.length - 1;
		numberOfRecords++;
		return (true);
	}

	function getRecord(string id) external view returns (string memory payload){
		if(!isRecord(id)) revert('record with this id does not exist');
		return (facts[id].payload);
	}

	function updateRecord(string id, string memory payload) external returns (bool success){
		if(!isRecord(id)) revert('record with this id does not exist');
		facts[id].payload = payload;
		return (true);
	}

	function getAllRecords() external view returns (string[] memory payloads) {
		string[] memory payloadss = new string[](numberOfRecords);
		for (uint i = 0; i < numberOfRecords; i++) {
			Block storage fact = facts[recordsList[i]];
			payloadss[i] = fact.payload;
		}
		return (payloadss);
	}

	function deleteRecord(string id) external returns (bool success) {
		if(!isRecord(id)) revert('record with this id does not exist');
		uint rowToDelete = facts[id].listPointer;
		string keyToMove = recordsList[recordsList.length-1];
		recordsList[rowToDelete] = keyToMove;
		facts[keyToMove].listPointer = rowToDelete;
		recordsList.pop();
		numberOfRecords--;
		return (true);
	}
}